version: '3.9'

services:
  synpress:
    container_name: synpress
    build: .
    environment:
      DISPLAY: display:0.0
      CYPRESS_TENDERLY_ACCESS_KEY: ${CYPRESS_TENDERLY_ACCESS_KEY}
      CYPRESS_TENDERLY_PROJECT: ${CYPRESS_TENDERLY_PROJECT}
      CYPRESS_TENDERLY_USER: ${CYPRESS_TENDERLY_USER}
      SECRET_WORDS: ${SECRET_WORDS}
    depends_on:
      - display
      - video
    entrypoint: []
    working_dir: /app
    volumes:
      - './tests/e2e/videos:/app/tests/e2e/videos'
    command: npm run ci
    networks:
      - x11

  display:
    container_name: display
    image: synthetixio/display:016121eafdfff448414894d0ca5a50b1d72b62eb-base
    environment:
      RUN_XTERM: 'no'
      DISPLAY_WIDTH: ${DISPLAY_WIDTH}
      DISPLAY_HEIGHT: ${DISPLAY_HEIGHT}
    ports:
      - '8080:8080'
    networks:
      - x11

  video:
    container_name: video
    image: synthetixio/video:457bb48776c3b14de232d9dda620ba9188dc40ac-base
    volumes:
      - './tests/e2e/videos-ci:/videos'
    environment:
      FILE_NAME: ci-full-video.mp4
      SE_SCREEN_WIDTH: ${DISPLAY_WIDTH}
      SE_SCREEN_HEIGHT: ${DISPLAY_HEIGHT}
    depends_on:
      - display
    networks:
      - x11

networks:
  x11:
